Handle bytes when listing fonts in VideoClip.py
I got a `TypeError` when calling `TextClip.list('font')`:

```
  File "/Users/me/.virtualenvs/project/lib/python3.4/site-packages/moviepy/video/VideoClip.py", line 1177, in <listcomp>
    return [l.decode('UTF-8')[8:] for l in lines if l.startswith("  Font:")]
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

So now I'm just passing `bytes` to the `startswith` function as it's operating on bytes. Then decoding to `UTF-8` before it's returned.

If I need to do anything else, let me know :) This was just a quickfix.