Explicit integral result when processing nchannel
The following bug was observed in python 3.5.2

```python
from moviepy.editor import AudioFileClip
clip = AudioFileClip("music.mp3")

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-8acdacb28938> in <module>()
      4 
      5 for i in ('./.tmp_clips/{0}.mp4'.format(n) for n in (0, 2)):
----> 6     clip = VideoFileClip(i, verbose=True)
      7     clip_objs.append(clip)

/usr/local/lib/python3.5/dist-packages/moviepy/video/io/VideoFileClip.py in __init__(self, filename, has_mask, audio, audio_buffersize, audio_fps, audio_nbytes, verbose)
     80                                        buffersize= audio_buffersize,
     81                                        fps = audio_fps,
---> 82                                        nbytes = audio_nbytes)
     83 
     84     def __del__(self):

/usr/local/lib/python3.5/dist-packages/moviepy/audio/io/AudioFileClip.py in __init__(self, filename, buffersize, nbytes, fps)
     61         self.filename = filename
     62         reader = FFMPEG_AudioReader(filename,fps=fps,nbytes=nbytes,
---> 63                                          buffersize=buffersize)
     64 
     65         self.reader = reader

/usr/local/lib/python3.5/dist-packages/moviepy/audio/io/readers.py in __init__(self, filename, buffersize, print_infos, fps, nbytes, nchannels)
     68         self.buffer_startframe = 1
     69         self.initialize()
---> 70         self.buffer_around(1)
     71 
     72 

/usr/local/lib/python3.5/dist-packages/moviepy/audio/io/readers.py in buffer_around(self, framenumber)
    232         else:
    233             self.seek(new_bufferstart)
--> 234             self.buffer =  self.read_chunk(self.buffersize)
    235 
    236         self.buffer_startframe = new_bufferstart

/usr/local/lib/python3.5/dist-packages/moviepy/audio/io/readers.py in read_chunk(self, chunksize)
    121         result = (1.0*result / 2**(8*self.nbytes-1)).\
    122                                  reshape((len(result)/self.nchannels,
--> 123                                           self.nchannels))
    124         #self.proc.stdout.flush()
    125         self.pos = self.pos+chunksize

TypeError: 'float' object cannot be interpreted as an integer
```

This bug is suppressed when explicitly declaring integer division in the "rechunk" function.
The "/" operator in python3 generates a decimal number which is the incorrect input type for
this function, hence the error. The "//" is also backwards compatible with python2 so wont cause
any version bugs.
edit is also backwards compatible with python2